# -*- coding: utf-8 -*-
"""demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xcJ-ZzkGRzvJi28f1tTrG88r4dilWL5A
"""

!pip install torchaudio transformers gradio scikit-learn pandas

!pip install gradio

"""### Import libraries"""

import os
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import torch
import torchaudio
import gradio as gr
from transformers import ASTModel, ASTFeatureExtractor, BertModel, BertTokenizer
from torch import nn

try:
    torchaudio.set_audio_backend("sox_io")
except Exception:
    pass

# ------------------------------------------------------------------
# Define model
# ------------------------------------------------------------------
class ASTBERTCrossAttentionRegressor(nn.Module):
    def __init__(self):
        super().__init__()
        self.ast = ASTModel.from_pretrained("MIT/ast-finetuned-audioset-10-10-0.4593")
        self.bert = BertModel.from_pretrained("bert-base-uncased")
        self.cross_attn = nn.MultiheadAttention(embed_dim=768, num_heads=8, batch_first=True)
        self.regressor = nn.Linear(768, 2)

    def forward(self, audio_inputs, text_inputs):
        audio_inputs = {k: v.to(self.ast.device) for k, v in audio_inputs.items()}
        text_inputs = {k: v.to(self.bert.device) for k, v in text_inputs.items()}
        a_seq = self.ast(**audio_inputs).last_hidden_state  # [B, T_a, 768]
        t_seq = self.bert(**text_inputs).last_hidden_state  # [B, T_t, 768]
        cross_out, _ = self.cross_attn(query=t_seq, key=a_seq, value=a_seq)
        fused = cross_out[:, 0, :]  # [B, 768] → [CLS]
        return self.regressor(fused)
# ------------------------------------------------------------------
# Load model
# ------------------------------------------------------------------
AST_WEIGHTS = "ast_bert_cross_half_training.pt"  # Weigthed model file

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model  = ASTBERTCrossAttentionRegressor().to(device)
model.load_state_dict(torch.load(AST_WEIGHTS, map_location=device))
model.eval()

# Processor & Tokenizer
ast_proc = ASTFeatureExtractor.from_pretrained("MIT/ast-finetuned-audioset-10-10-0.4593")
bert_tok = BertTokenizer.from_pretrained("bert-base-uncased")

# ------------------------------------------------------------------
# VA DB load
# ------------------------------------------------------------------

# Combined metadata file
VA_DB_PATH = "va_metadata_combined_cleaned.csv"  # Song, Valence, Arousal, ...
va_df = pd.read_csv(VA_DB_PATH)
va_vectors = va_df[["Valence", "Arousal"]].values.astype(float)  # [N, 2]
song_ids   = va_df["Song"].tolist()


audio_file_path = "/content/Music/audio"
song_audio_paths = [os.path.join(audio_file_path, f"{sid}.mp3") for sid in song_ids]


# ------------------------------------------------------------------
# Proprocessing Audio and lylics & VA predict
# ------------------------------------------------------------------

def preprocess_audio_text(audio_path, lyric_path, mode):
    # audio
    waveform, sr = torchaudio.load(audio_path)

    # Split from 10 to 30 sec
    if mode == "youtube":
        start_sample = int(10 * sr)
        end_sample = int(30 * sr)
        total_len = waveform.size(-1)
        print(total_len)
        if total_len > end_sample:
            waveform = waveform[:, start_sample:end_sample]
            print("[INFO] YouTube mode: 10s ~ 30s")
        elif total_len > start_sample:
            waveform = waveform[:, start_sample:]
            print("[INFO] YouTube mode: after 10s to end")
        else:
            print("[WARN] Audio too short (<10s), using full waveform")
    else:
        print("[INFO] Full audio used (mode:", mode, ")")

    if waveform.shape[0] > 1:
        waveform = waveform.mean(dim=0)
    elif waveform.shape[0] == 1:
        waveform = waveform.squeeze(0)
    if sr != 16000:
        waveform = torchaudio.transforms.Resample(orig_freq=sr, new_freq=16000)(waveform)
    audio_inputs = ast_proc(waveform, sampling_rate=16000, return_tensors="pt")
    audio_inputs = {k: v.squeeze(0).to(device) for k, v in audio_inputs.items()}


    text_inputs = bert_tok(lyric_path, return_tensors="pt", padding="max_length", truncation=True, max_length=128)
    text_inputs = {k: v.squeeze(0).to(device) for k, v in text_inputs.items()}

    return audio_inputs, text_inputs

# ------------------------------------------------------------------
# Recommendation function
# ------------------------------------------------------------------

def recommend(audio_path, lyrics_text, lyrics_file, mode, youtube_url):
    # audio_path: string path
    if mode == "manual":
        lyrics = lyrics_text
    elif mode == "upload" and lyrics_file is not None:
        with open(lyrics_file.name, "r", encoding="utf-8") as f:
            lyrics = f.read()
    elif mode == "youtube" and youtube_url.strip():
        audio_path, lyrics = download_youtube(youtube_url.strip(),
                                              languages=("en",),
                                              use_whisper=False)
    else:
        return [None]*5 + ["❗ Input the text or youtube link or upload the file"]

    audio_inputs, text_inputs = preprocess_audio_text(audio_path, lyrics, mode)
    print("audio_inputs:", audio_inputs)
    print("text_inputs:", text_inputs)

    with torch.no_grad():
        for k in audio_inputs:
            audio_inputs[k] = audio_inputs[k].unsqueeze(0)
        for k in text_inputs:
            text_inputs[k] = text_inputs[k].unsqueeze(0)
        output = model(audio_inputs, text_inputs)  # [1, 2]
        valence, arousal = output.squeeze().tolist()
    print(valence)
    print(arousal)
    query_va = np.array([[valence, arousal]])  # (1, 2)

    # Since cosine similarity alone gives a score of 1 for pairs like (0.51, 0.49) and (0.33, 0.33), they were mistakenly included in the recommendations, so we changed the logic.
    # Consider cosine + distance

    # sims = cosine_similarity(query_va, va_vectors)[0]
    # top_idx = np.argsort(sims)[::-1]
    alpha = 0.7   # cosine weight(0~1)

    # (query_va : shape (1,2),  va_vectors : shape (N,2))
    cos  = cosine_similarity(query_va, va_vectors)[0]     # (N,)
    dist = np.linalg.norm(va_vectors - query_va, axis=1)  # (N,)

    score = alpha * (1 - cos) + (1 - alpha) * dist        # Small is similar
    top_idx = np.argsort(score)

    recs = []
    paths = []

    for idx in top_idx:
        song_path = song_audio_paths[idx]
        if os.path.abspath(song_path) == os.path.abspath(audio_path):
            continue
        if len(recs) == 5:
            break
        paths.append(song_path)
        quadrant = va_df.iloc[idx]["Quadrant"]

        recs.append(f"{song_ids[idx]}  |  score={score[idx]:.2f}  |  V={va_vectors[idx][0]:.2f}, A={va_vectors[idx][1]:.2f}, Q={quadrant}")

    while len(paths) < 5:
        paths.append(None)
    print(paths)
    print(recs)
    return paths[0], paths[1], paths[2], paths[3], paths[4], "\n".join(recs)

!pip install yt-dlp youtube-transcript-api

"""### Audio download logic from a YouTube link + YouTube Script API call logic"""

from pathlib import Path
import yt_dlp, tempfile, os
from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled

def download_youtube(url: str, languages=("en", ), use_whisper=False):
    """
    Returns
    -------
    audio_path : str  # downloaded mp3 file
    lyrics     : str  # transcript text (empty if not available)
    """
    # 1) Download & convert to mp3
    ydl_opts = {
        "format": "bestaudio/best",
        "outtmpl": os.path.join(tempfile.gettempdir(), "%(id)s.%(ext)s"),
        "postprocessors": [{"key": "FFmpegExtractAudio",
                            "preferredcodec": "mp3",
                            "preferredquality": "192"}],
        "quiet": True,
    }
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        info        = ydl.extract_info(url, download=True)
        base        = Path(ydl.prepare_filename(info)).with_suffix(".mp3")
        audio_path  = str(base)
        video_id    = info["id"]

    # 2) Get transcript
    lyrics = ""
    try:
        transcript = YouTubeTranscriptApi.get_transcript(video_id,
                                                         languages=list(languages))
        lyrics = "\n".join(t["text"] for t in transcript)
    except TranscriptsDisabled:
        print("[WARN] transcripts disabled")
    except Exception as e:
        print(f"[WARN] transcript error: {e}")

    # # 3) Optional Whisper fallback
    # if not lyrics and use_whisper:
    #     lyrics = whisper_transcribe(audio_path, lang=languages[0])

    return audio_path, lyrics

"""### Gradio UI logic"""

with gr.Blocks(title="🎵 Recommendation based on Valence‑Arousal") as demo:
    gr.Markdown("##Upload a song + lyrics (paste or .txt) to get Top-5 emotionally similar tracks.")

    # (1) Audio upload
    audio_in = gr.Audio(type="filepath", label="🎧 Upload MP3/WAV")

    # (2) Select lyrics input method
    mode_radio = gr.Radio(["manual", "upload", "youtube"],
                          value="manual", label="Lyrics Input Mode")

    # (3) Components for Textbox / File upload
    lyrics_tb   = gr.Textbox(lines=8, label="📝 Paste Lyrics", visible=True)
    lyrics_file = gr.File(label="📄 Upload Lyrics (.txt)",
                          file_types=[".txt"], visible=False)
    youtube_tb  = gr.Textbox(label="▶️ YouTube URL", visible=False)   # ★ 추가

    # Toggle component visibility based on radio selection
    def _toggle(m):
        return (gr.update(visible=(m=="manual")),
                gr.update(visible=(m=="upload")),
                gr.update(visible=(m == "youtube"))
                )
    mode_radio.change(_toggle, inputs=mode_radio,
                      outputs=[lyrics_tb, lyrics_file, youtube_tb])

    # (4) Action button
    btn = gr.Button("🎧Get Recommendation")

    # (5) Output components (5 audio + 1 text)
    outs = [gr.Audio(label=f"🎵 Top {i+1}") for i in range(5)]
    outs.append(gr.Textbox(label="Top‑5 Emotionally Similar Songs"))

    # (6) Link click event to recommendation function
    btn.click(fn=recommend,
              inputs=[audio_in, lyrics_tb, lyrics_file, mode_radio, youtube_tb],
              outputs=outs)

demo.launch()